# Generated by Django 2.2.3 on 2019-07-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_contacts'),
        ('contacts', '0003_merge_20190214_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accounts',
            field=models.ManyToManyField(related_name='contacts', to='accounts.Account'),
        ),
    ]
