# Generated by Django 2.2.3 on 2019-07-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='accounts',
            new_name='account',
        ),
    ]
