# Generated by Django 2.2.2 on 2019-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_data',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
