# Generated by Django 2.2.2 on 2019-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_my_data_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_data',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
